services:
  - type: web
    name: Auto-Email-Responder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

cronJobs:
  - name: check-emails
    schedule: "*/10 * * * *"  # Runs every 10 minutes
    command: curl -X POST http://email-auto-responder.onrender.com/trigger